name: gofmt

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  gofmt:
    strategy:
      matrix:
        os:
          - ubuntu-latest
        go:
          - 1.20.x
          - 1.21.x
          - 1.22.x
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go }}
    - name: Run gofmt
      run: test -z "$(gofmt -l .)"
